"""Freeze the 12 human-labelled abstract-level exemplars into the prompt directory (§3.3, P0.3).

Production uses a FIXED exemplar set written into the prompt file (no severity_exemplars index, no retrieval): the
`few` condition of data/cases/experiments/abstract_fewshot.py, split(k=4, seed=7) -> 4 pairs per Brierley class.
Re-running this script must reproduce the same file; the evaluated accuracy (78.6%) refers to exactly these 12 pairs.

Usage: python claimdrift/scripts/export_abstract_exemplars.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "data" / "cases" / "experiments"))
import abstract_fewshot as AF  # noqa: E402

K, SEED = 4, 7


def main():
    pairs = AF.load_pairs()
    ex, test = AF.split(pairs, K, SEED)
    out = {"_doc": ("Fixed abstract-level exemplars (Brierley et al. 2022 labels, 4 annotators reconciled). "
                    f"abstract_fewshot.split(k={K}, seed={SEED}); order as shuffled by the split. Generated by "
                    "claimdrift/scripts/export_abstract_exemplars.py -- do not edit by hand."),
           "k": K, "seed": SEED, "n_test_pairs": len(test),
           "exemplars": [{k: e[k] for k in ("doi", "pre", "pub", "class", "annotator_notes")} for e in ex]}
    path = ROOT / "claimdrift" / "prompts" / "abstract_exemplars.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"wrote {len(ex)} exemplars ({[e['class'] for e in ex]}) -> {path}")


if __name__ == "__main__":
    main()
